# Execute your favorite apps at launch
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = bash /home/thomas/bin/polkit_wrapper.sh
exec-once = hyprctl setcursor Adwaita 24
exec-once = waybar
exec-once = hyprpaper
exec-once = seafile-applet & blueman-applet & nm-applet --indicator
exec-once = bash /home/thomas/bin/hyprland-socket-handler.sh 2>&1 >> /tmp/hyprland-socket-handler.log
exec-once = [workspace 2] /home/thomas/bin/mainkitty.sh
# exec-once = [workspace 3 silent] chromium --password-store=gnome-libsecret
# don't know why the above does not work anymore, but for now we need to use a dirty workaround
exec-once = sh -c 'chromium --password-store=gnome-libsecret & while ! hyprctl clients | grep -q "class: chromium"; do sleep 0.1; done; hyprctl dispatch movetoworkspacesilent 3,class:^chromium$'
exec-once = hypridle 
exec-once = hyprland-autoname-workspaces &> /tmp/hyprland-autoname-workspaces.log
