# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppress_event maximize, match:class .* # You'll probably like this.
windowrule = workspace 4, match:class (geany)
windowrule = workspace 9 silent, match:initial_title (.*youtube.*)

windowrule = float on, move ((monitor_w*0.25)) ((monitor_h*0.25)), match:class (org\.tug\.texworks)

windowrule = float on, size (monitor_w*0.5) $screenheight_waybar, move (0) (30), match:title ^(.*\.tex\*? - TeXworks)$

windowrule = float on, size (monitor_w*0.5) $screenheight_waybar, move ((monitor_w*0.5)) (30), match:title ^(.*\.pdf - TeXworks)$

windowrule = workspace 8, match:initial_title Microsoft Teams.*

windowrule = workspace 10 silent, match:class (steam)

workspace = w[t1], gapsout:0, gapsin:0
workspace = w[tg1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[t1]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[tg1]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace f[1]

windowrule = workspace 4 silent, match:class (^cassowaryApp-.*)
