[font]
size=14.0
normal = { family = "Hack Nerd Font", style = "Regular" }

[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[window]
opacity = 0.9
startup_mode = "Maximized"

[keyboard]
bindings = [
  { key = "L", mods = "Control", action = "ReceiveChar" },
]

[general]
live_config_reload = true
