live_config_reload = true


[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[window]
opacity = 0.9

[keyboard]
bindings = [
  { key = "L", mods = "Control", action = "ReceiveChar" },
]
